# Generated by Django 5.2.7 on 2025-11-25 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('ONG', 'ONG'), ('Foundation', 'FOUNDATION'), ('Social Enterprise', 'SOCIAL_ENTERPRISE'), ('Cooperative', 'COOPERATIVE'), ('Other', 'OTHER')], max_length=20)),
                ('legal_entity_number', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('focus_area', models.CharField(choices=[('Education', 'EDUCATION'), ('Health', 'HEALTH'), ('Environment', 'ENVIRONMENT'), ('Community Development', 'COMMUNITY_DEVELOPMENT'), ('Technology', 'TECHNOLOGY'), ('Arts and Culture', 'ARTS_AND_CULTURE'), ('Other', 'OTHER')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
