# Generated by Django 5.2.7 on 2025-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='user',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='legal_entity_number',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='canton',
            field=models.CharField(default='SJ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='district',
            field=models.CharField(default='RUUCACA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='casa@casa.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='experience_years',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_rep_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_representative',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='911', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='province',
            field=models.CharField(default='SJ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(default='1234', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='focus_area',
            field=models.CharField(choices=[('Educación', 'Educación'), ('Salud', 'Salud'), ('Medio Ambiente', 'Medio Ambiente'), ('Desarrollo Comunitario', 'Desarrollo Comunitario'), ('Tecnología', 'Tecnología'), ('Arte y Cultura', 'Arte y Cultura'), ('Otra', 'Otra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('ONG', 'ONG'), ('Fundación', 'Fundación'), ('Empresa Social', 'Empresa Social'), ('Cooperativa', 'Cooperativa'), ('Otra', 'Otra')], max_length=50),
        ),
    ]
