# Generated by Django 5.2.7 on 2025-12-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rename_user_organization_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='province',
            field=models.CharField(choices=[('San José', 'San José'), ('Alajuela', 'Alajuela'), ('Cartago', 'Cartago'), ('Heredia', 'Heredia'), ('Guanacaste', 'Guanacaste'), ('Puntarenas', 'Puntarenas'), ('Limón', 'Limón')], max_length=100),
        ),
    ]
