# Generated by Django 5.2.7 on 2025-12-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_contact_email_campaign_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pdf_documents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
