# Generated by Django 5.2.7 on 2025-12-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_active',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(choices=[('active', 'Active'), ('detained', 'Detained'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
