# Generated by Django 5.2.7 on 2025-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaign_is_active_campaign_campaign_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='review_comment',
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_sections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
