# Generated by Django 5.2.7 on 2025-12-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_campaign_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
