# Generated by Django 5.2.7 on 2025-12-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
