# Generated by Django 5.2.7 on 2025-12-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='proof_of_payment_description',
            field=models.TextField(blank=True, help_text='Descripción del comprobante de pago (referencia, número de transacción, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='proof_of_payment_url',
            field=models.URLField(blank=True, help_text='URL de Cloudinary del comprobante de pago', null=True),
        ),
    ]
