# Generated by Django on 2025-12-17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='proof_of_payment_name',
            field=models.CharField(blank=True, max_length=255, null=True, help_text='Nombre de archivo del comprobante de pago'),
        ),
    ]
