# Generated by Django 5.2.7 on 2025-12-17 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_donation_proof_of_payment_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de aprobación', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin que aprobó la donación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Estado de aprobación de la donación', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo del rechazo', null=True),
        ),
    ]
