# Generated by Django 5.2.7 on 2025-12-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_merge_0009_add_and_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('sinpe_movil', 'SINPE Móvil'), ('bank_transfer_bcr', 'Transferencia Bancaria - BCR'), ('bank_transfer_bn', 'Transferencia Bancaria - Banco Nacional'), ('bank_transfer_bac', 'Transferencia Bancaria - BAC'), ('bank_transfer_other', 'Transferencia Bancaria - Otro Banco')], max_length=50),
        ),
    ]
