# Generated by Django 5.2.7 on 2025-12-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_userreport_reported_user'),
        ('campaigns', '0013_userreport'),
    ]

    operations = [
    ]
