# Generated by Django 5.2.7 on 2025-12-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_campaignfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='province',
            field=models.CharField(choices=[('San José', 'San José'), ('Alajuela', 'Alajuela'), ('Cartago', 'Cartago'), ('Heredia', 'Heredia'), ('Guanacaste', 'Guanacaste'), ('Puntarenas', 'Puntarenas'), ('Limón', 'Limón')], default='San José', max_length=50),
        ),
    ]
