# Generated by Django 5.2.7 on 2025-12-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_campaign_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lives_impact_estimate',
            field=models.IntegerField(blank=True, help_text='Estimado de vidas a impactar', null=True),
        ),
    ]
