# Generated by Django 5.2.7 on 2025-11-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Contributor', 'CONTRIBUTOR'), ('Admin', 'ADMIN'), ('CampaignManager', 'CAMPAIGNMANAGER'), ('User', 'USER')], max_length=20),
        ),
    ]
