# Generated by Django 5.2.7 on 2025-11-14 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1996-09-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='MALE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='goverment_ID',
            field=models.CharField(default='116540496', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Key_interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('Environment', 'ENVIRONMENT'), ('Education', 'EDUCATION'), ('Health', 'HEALTH'), ('Animal Welfare', 'ANIMAL_WELFARE'), ('Arts and Culture', 'ARTS_AND_CULTURE'), ('Community Development', 'COMMUNITY_DEVELOPMENT'), ('Science and Technology', 'SCIENCE_AND_TECHNOLOGY'), ('Sports and Recreation', 'SPORTS_AND_RECREATION'), ('Other', 'OTHER')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
