# Generated by Django 5.2.7 on 2025-11-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_recoverycode_delete_nationality_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-23'),
            preserve_default=False,
        ),
    ]
