# Generated by Django 5.2.7 on 2025-11-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycode',
            name='created_at',
        ),
    ]
