# Generated by Django 5.2.7 on 2025-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rejectionreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionreason',
            name='rejection_reason',
            field=models.TextField(default='No se especificó motivo'),
        ),
    ]
